### PR TITLE
controller: make parameter really work with cli module

### PR DESCRIPTION
**Pull request by Vicente-Cheng**
- `DefaulText` is real text. That shows on `--help`. `Value` does really for the default value.
       Actually, if the `DefaultText` is nil, that would get the `Value` for it.

Signed-off-by: Vicente Cheng <vicente.cheng@suse.com>

### CODE REVIEW

**Comment by Vicente-Cheng** [comment]
That is the related fix for https://github.com/harvester/harvester/issues/1831

**Comment by bk201** [comment]
To be complete, we also need to add the `NDM_MAX_CONCURRENT_OPS` environment variable in the chart template: https://github.com/harvester/charts/blob/master/charts/harvester-node-disk-manager/templates/daemonset.yaml

**Comment by Vicente-Cheng** [comment]
> To be complete, we also need to add the `NDM_MAX_CONCURRENT_OPS` environment variable in the chart template: https://github.com/harvester/charts/blob/master/charts/harvester-node-disk-manager/templates/daemonset.yaml

Thanks for the reminder, done.

**Review by guangbochen — APPROVED** [review]
LGTM

**Review by bk201 — APPROVED** [review]
LGTM, work as expect.

**Pull request merged**
