### PR TITLE
build(image): bump sle bci to 15.4

### PR DESCRIPTION
**Pull request by starbops**
Signed-off-by: Zespre Chang <zespre.chang@suse.com>

harvester/harvester#3149

### CODE REVIEW

**Review by bk201 — APPROVED** [review]
LGTM

**Comment by Vicente-Cheng** [comment]
Hi @starbops, 
Could you rebase and push again?
Thanks!

**Comment by starbops** [comment]
Rebase the PR, please check again. Thanks!

**Review by Vicente-Cheng — APPROVED** [review]
LGTM, wait for CI runs to be completed.

**Pull request merged**
