### PR TITLE
fix: set LHv2 DiskDriver to "auto" if unset

### PR DESCRIPTION
**Pull request by tserong**
**Problem:**
We need to force DiskDriver to "auto" if it's not explicitly set, because Longhorn also does that internally.  If we don't do this, the subsequent `reflect.DeepEqual()` in `LonghornV2Provisioner.Update()` will always fail because we have an empty string, but the LHN CR will have it set to "auto" which results in a weird resync loop.

**Solution:**
This PR.

**Related Issue:**
https://github.com/harvester/harvester/issues/6709

**Test plan:**
Add an LHv2 disk. Verify we don't see the errors mentioned in the related issue.

### CODE REVIEW

**Comment by tserong** [comment]
https://github.com/bk201/vagrant-k3s/pull/3 should fix that CI failure

**Review by Vicente-Cheng — APPROVED** [review]
LGTM, thanks!

**Review by bk201 — APPROVED** [review]

**Comment by tserong** [comment]
latest CI failure is:

```
=== RUN   TestSingleDiskOperation/Test_1_UnprovisionSingleDisk
    test_0_single_disk_test.go:141: 
        	Error Trace:	/home/github/actions-runner/_work/node-disk-manager/node-disk-manager/tests/integration/test_0_single_disk_test.go:141
        	Error:      	Not equal: 
        	            	expected: "/var/lib/harvester/extra-disks/9665fd40086d48e7ca541b1e990c6645"
        	            	actual  : ""
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1 +1 @@
        	            	-/var/lib/harvester/extra-disks/9665fd40086d48e7ca541b1e990c6645
        	            	+
        	Test:       	TestSingleDiskOperation/Test_1_UnprovisionSingleDisk
        	Messages:   	Mountpoint should be empty after we remove disk!
```

I suspect this is probably because `Test_1_UnprovisionSingleDisk()` is still setting `Spec.FileSystem.Provisioned = false` rather than `Spec.Provision = false`, and is unrelated to this PR.

**Comment by Vicente-Cheng** [comment]
Yeah, and it should be fixed on #151. I thought we could merge it and let CI re-run with the master branch

**Pull request merged**
