### PR TITLE
packages: update copyright to 2024

### PR DESCRIPTION
**Pull request by Vicente-Cheng**
**Problem:**
Validation failure due to copyright not matching.

**Solution:**
update copyright

**Related Issue:**

**Test plan:**
Just make sure the CI passed

### CODE REVIEW

**Review by tserong — APPROVED** [review]
LGTM. I'm curious though - where can I see the failed validation that necessitated this change?

**Comment by Vicente-Cheng** [comment]
> LGTM. I'm curious though - where can I see the failed validation that necessitated this change?

The [validate-ci](https://github.com/harvester/node-disk-manager/blob/master/scripts/validate-ci) will check the generated code should be the same as the current one. If not, it will return an error.

**Comment by tserong** [comment]
Got it, thanks @Vicente-Cheng!

**Review by bk201 — APPROVED** [review]

**Comment by Vicente-Cheng** [comment]
@Mergifyio backport v0.5.x

**Comment by Vicente-Cheng** [comment]
@Mergifyio backport v0.6.x

**Pull request merged**
